/**
 * Auto-generated by GraphQL Codegen.
 * Run: npm run codegen
 *
 * Types placeholder - regenerate with: shopify hydrogen codegen
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };

export interface Product {
  id: string;
  handle: string;
  title: string;
  description?: Maybe<string>;
  descriptionHtml?: Maybe<string>;
  vendor?: Maybe<string>;
  productType?: Maybe<string>;
  tags?: Maybe<string[]>;
  featuredImage?: Maybe<Image>;
  images?: Maybe<ImageConnection>;
  priceRange?: Maybe<ProductPriceRange>;
  compareAtPriceRange?: Maybe<ProductPriceRange>;
  options?: Maybe<ProductOption[]>;
  variants?: Maybe<ProductVariantConnection>;
  seo?: Maybe<SEO>;
  metafields?: Maybe<Metafield[]>;
}

export interface ProductVariant {
  id: string;
  title?: Maybe<string>;
  availableForSale?: Maybe<boolean>;
  selectedOptions?: Maybe<SelectedOption[]>;
  price?: Maybe<MoneyV2>;
  compareAtPrice?: Maybe<MoneyV2>;
  image?: Maybe<Image>;
}

export interface ProductOption {
  name: string;
  values: string[];
}

export interface Image {
  url: string;
  altText?: Maybe<string>;
  width?: Maybe<number>;
  height?: Maybe<number>;
}

export interface MoneyV2 {
  amount: string;
  currencyCode: string;
}

export interface ProductPriceRange {
  minVariantPrice: MoneyV2;
  maxVariantPrice?: Maybe<MoneyV2>;
}

export interface Metafield {
  namespace: string;
  key: string;
  value: string;
  type?: Maybe<string>;
}

export interface SEO {
  title?: Maybe<string>;
  description?: Maybe<string>;
}

export interface SelectedOption {
  name: string;
  value: string;
}

export interface ImageConnection {
  nodes: Image[];
}

export interface ProductVariantConnection {
  nodes: ProductVariant[];
}

export interface Collection {
  id: string;
  handle: string;
  title: string;
  description?: Maybe<string>;
  seo?: Maybe<SEO>;
  products?: Maybe<ProductConnection>;
}

export interface ProductConnection {
  nodes: Product[];
  pageInfo: PageInfo;
}

export interface PageInfo {
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  startCursor?: Maybe<string>;
  endCursor?: Maybe<string>;
}
